[project]
name = "ele-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.73.1",
    "grpcio-tools>=1.73.1",
]
